export const UPDATE_NOTES = 'UPDATE_NOTES';
export const FETCH_NOTES = 'FETCH_NOTES';
export const ERROR_FETCH_NOTES = 'ERROR_FETCH_NOTES';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const UPDATE_EDITABLE_NOTE = 'UPDATE_EDITABLE_NOTE';
export const SAVE_NOTE = 'SAVE_NOTE';
export const ERROR_SAVE_NOTE = 'ERROR_SAVE_NOTE';
