export const UPDATE_LABELS = 'UPDATE_LABELS';
export const FETCH_LABELS = 'FETCH_LABELS';
export const ERROR_FETCH_LABELS = 'ERROR_FETCH_LABELS';
export const SELECT_LABEL = 'SELECT_LABEL';
export const UPDATE_EDITABLE_LABEL = 'UPDATE_EDITABLE_LABEL';
export const UPDATE_MODAL_LABEL = 'UPDATE_MODAL_LABEL';
export const SAVE_LABEL = 'SAVE_LABEL';
export const ERROR_SAVE_LABEL = 'ERROR_SAVE_LABEL';

